language: node_js
node_js: ["7"]

cache:
  yarn: true

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  
install:
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn coverage
  - yarn release
